---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  POSTGRES_DB: {{.Values.secret.db | default "postgresdb"  | b64enc }}
  POSTGRES_USER: {{.Values.secret.user | default "admin"  | b64enc }}
  POSTGRES_PASSWORD: {{.Values.secret.pass | default "admin"  | b64enc }}