apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range .Values.service.ports }}
    - name: {{.name}}
      targetPort: {{.name}}
      port: {{.port}}
      protocol: {{.protocol}}
  {{- end }}
  selector:
    {{- include "postgres.selectorLabels" . | nindent 4 }}
