
{{- if or $.Values.additional_resources $.Values.templates -}}
  {{- range $.Values.additional_resources }}
---{{- toYaml . | nindent 0 }}
  {{- end }}
  {{- range $.Values.templates }}
---{{- (tpl . $)  | nindent 0 }}
  {{- end }}
{{- end -}}