
{{- if or $.Values.additional_resources $.Values.templates -}}
  {{- range $.Values.resources }}
---{{- toYaml (merge . $base) | nindent 0 }}
  {{- end }}
  {{- range $.Values.templates }}
---{{- (tpl . $)  | nindent 0 }}
  {{- end }}
{{- end -}}