{{- with .Values.secrets }}
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .name }}
  labels:
    {{- include "generic.labels" . | nindent 4 }}
spec:
  itemPath: {{.itemPath}}
