{{- range .Values.persistence }}
{{- if .enabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "generic.fullname" $ }}-{{ .name }}
  labels:
    {{- include "generic.labels" $ | nindent 4 }}
spec:
  accessModes:
    - {{ .accessMode | default "ReadWriteOnce" | quote }}
  resources:
    requests:
      storage: {{ .size | quote }}
  {{- if .storageClass }}
  {{- if (eq "-" .storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .storageClass }}"
  {{- end }}
  {{- end }}
---
{{- end }}
{{- end }}
