{{ if (default .Values.redis false) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "generic.fullname" . }}-redis
  labels:
    {{- include "generic.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7.2
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "128Mi"
          volumeMounts:
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-data
          emptyDir: {}   # ersetzt später durch PersistentVolumeClaim
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    {{- include "generic.labels" . | nindent 4 }}
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
{{ end }}