{{- if .Values.tailscale.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "generic.fullname" . }}-tailscale
  labels:
    {{- include "generic.labels" . | nindent 4 }}
  {{- with .Values.tailscale.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
    - port: {{ .Values.tailscale.port | default .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "generic.selectorLabels" . | nindent 4 }}
{{- end }}
